### ISSUE TITLE
libmqp needs 2 successive calls of cmake to be built

### ISSUE THREAD

**Issue by EricDeveaud** [soedinglab/hh-suite#64]
trying to build  hhsuite-3.0-beta.2 from following archive: https://github.com/soedinglab/hh-suite/releases/download/v3.0-beta.2/hhsuite-3.0-beta.2-Source.tar.gz
on centos-6.9

build was done this way:

```
cmake -DCMAKE_INSTALL_PREFIX=/exe/hhsuite/3.0-beta.2 -G "Unix Makefiles" /src/hhsuite/hhsuite-3.0.1-Source 2>&1 
make
```

it breaks with 

```
[ 73%] Building CXX object src/CMakeFiles/cstranslate_mpi.dir/cs/cstranslate_mpi_app.cc.o
Linking CXX executable ../bin/cstranslate_mpi
/usr/bin/ld: cannot find -lmpq
collect2: error: ld returned 1 exit status
```

we have to issue cmake  twice before calling make in order to have lib/libmpq.a the build succesfully end.

looks like first iteration does not generate rules for  libmpq.a build
while second one does.

see: 

-=-=- One cmake iteration -=-=-

```
bigmess:/tmp > tar xf hhsuite-3.0-beta.2-Source.tar.gz 
bigmess:/tmp > cd hhsuite-3.0.1-Source
bigmess:/tmp/hhsuite-3.0.1-Source > mkdir build-once
bigmess:/tmp/hhsuite-3.0.1-Source > cd build-once 
bigmess:hhsuite-3.0.1-Source/build-once > cmake -G "Unix Makefiles"  ../
-- The CXX compiler identification is GNU 4.9.0
-- Check for working CXX compiler: /local/gensoft2/exe/gcc/4.9.0/bin/c++
-- Check for working CXX compiler: /local/gensoft2/exe/gcc/4.9.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler is GNU 
-- Using CPU native flags for SSE optimization:  -march=native
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Success
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Success
-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Success
-- Performing Test HAVE_SSSE3_EXTENSIONS
-- Performing Test HAVE_SSSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Success
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Success
-- Found AVXextensions, using flags:  -march=native -mavx -mfpmath=sse -Wa,-q
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- The C compiler identification is GNU 4.9.0
-- Check for working C compiler: /local/gensoft2/exe/gcc/4.9.0/bin/cc
-- Check for working C compiler: /local/gensoft2/exe/gcc/4.9.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for fmemopen
-- Looking for fmemopen - found
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES) 
-- Found MPI_CXX: /local/gensoft2/exe/openmpi/2.0.1/lib/libmpi.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/hhsuite-3.0.1-Source/build-once
bigmess:hhsuite-3.0.1-Source/build-once > make help
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... install/strip
... edit_cache
... rebuild_cache
... install
... list_install_components
... package
... test
... package_source
... install/local
... cstranslate
... hhviterbialgorithm_and_ss
... hhblits
... CS_OBJECTS
... hhviterbialgorithm_with_celloff
... hhmake
... a3m_extract
... hhblits_omp
... hhalign
... hhconsensus
... HH_OBJECTS
... a3m_database_filter
... A3M_COMPRESS_OBJECT
... a3m_database_extract
... hhfilter
... a3m_database_reduce
... hhviterbialgorithm_with_celloff_and_ss
... hhsearch
... cstranslate_mpi
... a3m_reduce
... ffindex_shared
... ffindex_apply_mpi
... ffindex_get
... ffindex_from_fasta
... ffindex_order
... ffindex_unpack
... ffindex_apply
... ffindex_modify
... ffindex
... ffindex_build
```
with this make ends with following error

```
[ 70%] Built target hhviterbialgorithm_and_ss
Scanning dependencies of target cstranslate
[ 72%] Building CXX object src/CMakeFiles/cstranslate.dir/cs/cstranslate_app.cc.o
Linking CXX executable ../bin/cstranslate
[ 72%] Built target cstranslate
Scanning dependencies of target cstranslate_mpi
[ 73%] Building CXX object src/CMakeFiles/cstranslate_mpi.dir/cs/cstranslate_mpi_app.cc.o
Linking CXX executable ../bin/cstranslate_mpi
/usr/bin/ld: cannot find -lmpq
collect2: error: ld returned 1 exit status
```

-=-=- two cmake iterations -=-=-
while 2 successives calls to cmake does the job

```
bigmess:hhsuite-3.0.1-Source/build-once > cd ../
bigmess:/tmp/hhsuite-3.0.1-Source > mkdir build-twice
bigmess:/tmp/hhsuite-3.0.1-Source > cd build-twice
bigmess:hhsuite-3.0.1-Source/build-twice > cmake -G "Unix Makefiles"  ../
-- The CXX compiler identification is GNU 4.9.0
-- Check for working CXX compiler: /local/gensoft2/exe/gcc/4.9.0/bin/c++
-- Check for working CXX compiler: /local/gensoft2/exe/gcc/4.9.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiler is GNU 
-- Using CPU native flags for SSE optimization:  -march=native
-- Performing Test HAVE_MM_MALLOC
-- Performing Test HAVE_MM_MALLOC - Success
-- Performing Test HAVE_POSIX_MEMALIGN
-- Performing Test HAVE_POSIX_MEMALIGN - Success
-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Failed
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Success
-- Performing Test HAVE_SSSE3_EXTENSIONS
-- Performing Test HAVE_SSSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Success
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Success
-- Found AVXextensions, using flags:  -march=native -mavx -mfpmath=sse -Wa,-q
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found OpenMP
-- The C compiler identification is GNU 4.9.0
-- Check for working C compiler: /local/gensoft2/exe/gcc/4.9.0/bin/cc
-- Check for working C compiler: /local/gensoft2/exe/gcc/4.9.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for fmemopen
-- Looking for fmemopen - found
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES) 
-- Found MPI_CXX: /local/gensoft2/exe/openmpi/2.0.1/lib/libmpi.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/hhsuite-3.0.1-Source/build-twice
bigmess:hhsuite-3.0.1-Source/build-twice > make help 
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... install/strip
... edit_cache
... rebuild_cache
... install
... list_install_components
... package
... test
... package_source
... install/local
... cstranslate
... hhviterbialgorithm_and_ss
... hhblits
... CS_OBJECTS
... hhviterbialgorithm_with_celloff
... hhmake
... a3m_extract
... hhblits_omp
... hhalign
... hhconsensus
... HH_OBJECTS
... a3m_database_filter
... A3M_COMPRESS_OBJECT
... a3m_database_extract
... hhfilter
... a3m_database_reduce
... hhviterbialgorithm_with_celloff_and_ss
... hhsearch
... cstranslate_mpi
... a3m_reduce
... ffindex_shared
... ffindex_apply_mpi
... ffindex_get
... ffindex_from_fasta
... ffindex_order
... ffindex_unpack
... ffindex_apply
... ffindex_modify
... ffindex
... ffindex_build
bigmess:hhsuite-3.0.1-Source/build-twice > cmake -G "Unix Makefiles"  ../
-- Compiler is GNU 
-- Using CPU native flags for SSE optimization:  -march=native
-- Found AVXextensions, using flags:  -march=native -mavx -mfpmath=sse -Wa,-q
-- Found OpenMP
-- Found MPI_C: /local/gensoft2/exe/openmpi/2.0.1/lib/libmpi.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/hhsuite-3.0.1-Source/build-twice
bigmess:hhsuite-3.0.1-Source/build-twice > make help 
The following are some of the valid targets for this Makefile:
... all (the default if no target is provided)
... clean
... depend
... install/strip
... edit_cache
... rebuild_cache
... install
... list_install_components
... package
... test
... package_source
... install/local
... cstranslate
... hhviterbialgorithm_and_ss
... hhblits
... CS_OBJECTS
... hhviterbialgorithm_with_celloff
... hhmake
... a3m_extract
... hhblits_omp
... hhalign
... hhconsensus
... HH_OBJECTS
... a3m_database_filter
... A3M_COMPRESS_OBJECT
... a3m_database_extract
... hhfilter
... a3m_database_reduce
... hhviterbialgorithm_with_celloff_and_ss
... hhsearch
... cstranslate_mpi
... a3m_reduce
... ffindex_shared
... ffindex_apply_mpi
... ffindex_get
... ffindex_from_fasta
... ffindex_order
... ffindex_unpack
... ffindex_apply
... ffindex_modify
... ffindex
... ffindex_build
... mpq
```

and then make successfully ends.

```
Scanning dependencies of target ffindex_unpack
[100%] Building C object lib/ffindex/src/CMakeFiles/ffindex_unpack.dir/ffindex_unpack.c.o
Linking C executable ../../../bin/ffindex_unpack
[100%] Built target ffindex_unpack
```

**Comment by milot-mirdita** [comment]
What cmake version are you using? Please run `cmake --version`.

**Comment by EricDeveaud** [comment]
cmake-3.2.1 

```
bigmess:hhsuite/hhsuite-3.0-beta.2 > cmake --version 
cmake version 3.2.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

and had the same behaviour with cmake-2.8.12.2

**Comment by milot-mirdita** [comment]
Hi Eric,

Sorry, I did not notice you were using one of the releases, instead of the latest git version.
Please checkout the latest version from git and use that to build the hh-suite. Your issue was resolved there.

Best regards,
Milot

**Comment by EricDeveaud** [comment]
Milot, 

we prefer to work and install from tagged releases.
as far as we can using a git clone is not on our policy. 

best

Eric

**Comment by meiermark** [comment]
Hello,

i just made a new release... can you check if the bug still persists?

Best wishes,
Markus

**Comment by SmartBioInf** [comment]
Hello,

it seems that this issue is back in the version v3.3.0-32-gfe1bb9a commit fe1bb9a2ef21f154c2b42f336e52f6004a2012b6

Two iterations of cmake solve the problem.

#### cmake

```
cmake -DCMAKE_INSTALL_PREFIX=. ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Compiler is GNU
-- Looking for fmemopen
-- Looking for fmemopen - found
-- Performing Test HAVE_AVX2_EXTENSIONS
-- Performing Test HAVE_AVX2_EXTENSIONS - Success
-- Performing Test HAVE_AVX_EXTENSIONS
-- Performing Test HAVE_AVX_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_2_EXTENSIONS
-- Performing Test HAVE_SSE4_2_EXTENSIONS - Success
-- Performing Test HAVE_SSE4_1_EXTENSIONS
-- Performing Test HAVE_SSE4_1_EXTENSIONS - Success
-- Performing Test HAVE_SSE3_EXTENSIONS
-- Performing Test HAVE_SSE3_EXTENSIONS - Success
-- Performing Test HAVE_SSE2_EXTENSIONS
-- Performing Test HAVE_SSE2_EXTENSIONS - Success
-- Performing Test HAVE_SSE_EXTENSIONS
-- Performing Test HAVE_SSE_EXTENSIONS - Success
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Found OpenMP
-- Configuring done
-- Generating done
-- Build files have been written to: .../hh-suite/build
```

#### make && install

```
make -j 4 && make install
Scanning dependencies of target hhviterbialgorithm_with_celloff_and_ss
Scanning dependencies of target A3M_COMPRESS
Scanning dependencies of target ffindex
[  1%] Scanning dependencies of target generated
Building CXX object src/CMakeFiles/A3M_COMPRESS.dir/a3m_compress.cpp.o
[  2%] Building C object lib/ffindex/src/CMakeFiles/ffindex.dir/ffindex.c.o
[  4%] Generating ../generated/context_data.crf.h
[  5%] Building CXX object src/CMakeFiles/hhviterbialgorithm_with_celloff_and_ss.dir/hhviterbialgorithm.cpp.o
[  6%] Building C object lib/ffindex/src/CMakeFiles/ffindex.dir/ffutil.c.o
Linking C static library libffindex.a
[  6%] Built target ffindex
[  8%] Generating ../generated/context_data.lib.h
Linking CXX static library libA3M_COMPRESS.a
[  8%] Built target A3M_COMPRESS
[  9%] Generating ../generated/cs219.lib.h
Scanning dependencies of target CS_OBJECTS
Linking CXX static library libhhviterbialgorithm_with_celloff_and_ss.a
[ 10%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/aa.cc.o
[ 10%] Built target hhviterbialgorithm_with_celloff_and_ss
[ 12%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/as.cc.o
[ 13%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/assert_helpers.cc.o
[ 16%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/getopt_pp.cc.o
[ 16%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/blosum_matrix.cc.o
[ 16%] Built target generated
Scanning dependencies of target hhviterbialgorithm_and_ss
Scanning dependencies of target hhviterbialgorithm_with_celloff
[ 17%] Building CXX object src/CMakeFiles/hhviterbialgorithm_and_ss.dir/hhviterbialgorithm.cpp.o
[ 18%] Building CXX object src/CMakeFiles/hhviterbialgorithm_with_celloff.dir/hhviterbialgorithm.cpp.o
Scanning dependencies of target a3m_database_extract
[ 20%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/log.cc.o
[ 21%] Building CXX object src/CMakeFiles/a3m_database_extract.dir/a3m_database_extract.cpp.o
[ 22%] Building CXX object src/cs/CMakeFiles/CS_OBJECTS.dir/application.cc.o
Linking CXX executable a3m_database_extract
Linking CXX static library libhhviterbialgorithm_with_celloff.a
[ 22%] Built target a3m_database_extract
Scanning dependencies of target a3m_database_filter
Linking CXX static library libhhviterbialgorithm_and_ss.a
[ 22%] Built target hhviterbialgorithm_with_celloff
[ 24%] Building CXX object src/CMakeFiles/a3m_database_filter.dir/a3m_database_filter.cpp.o
Scanning dependencies of target a3m_database_reduce
[ 24%] Built target hhviterbialgorithm_and_ss
Scanning dependencies of target a3m_extract
[ 25%] Building CXX object src/CMakeFiles/a3m_database_reduce.dir/a3m_database_reduce.cpp.o
[ 27%] Building CXX object src/CMakeFiles/a3m_extract.dir/a3m_extract.cpp.o
Linking CXX static library libCS_OBJECTS.a
[ 27%] Built target CS_OBJECTS
Scanning dependencies of target a3m_reduce
[ 28%] Building CXX object src/CMakeFiles/a3m_reduce.dir/a3m_reduce.cpp.o
Linking CXX executable a3m_extract
Linking CXX executable a3m_database_reduce
Linking CXX executable a3m_database_filter
[ 28%] Built target a3m_extract
Scanning dependencies of target ffindex_apply
[ 28%] [ 28%] Built target a3m_database_reduce
Built target a3m_database_filter
Scanning dependencies of target ffindex_build
Scanning dependencies of target ffindex_from_fasta
[ 29%] Building C object lib/ffindex/src/CMakeFiles/ffindex_apply.dir/ffindex_apply_mpi.c.o
Linking CXX executable a3m_reduce
[ 31%] Building C object lib/ffindex/src/CMakeFiles/ffindex_build.dir/ffindex_build.c.o
[ 32%] Building C object lib/ffindex/src/CMakeFiles/ffindex_from_fasta.dir/ffindex_from_fasta.c.o
Linking C executable ffindex_apply
Linking C executable ffindex_build
[ 32%] Built target a3m_reduce
Linking C executable ffindex_from_fasta
[ 32%] Built target ffindex_apply
Scanning dependencies of target ffindex_from_fasta_with_split
[ 32%] Built target ffindex_build
Scanning dependencies of target ffindex_get
Scanning dependencies of target ffindex_modify
[ 33%] [ 33%] Built target ffindex_from_fasta
Building C object lib/ffindex/src/CMakeFiles/ffindex_from_fasta_with_split.dir/ffindex_from_fasta_with_split.c.o
Scanning dependencies of target ffindex_order
[ 36%] [ 36%] [ 37%] Building C object lib/ffindex/src/CMakeFiles/ffindex_get.dir/ffindex_get.c.o
Building C object lib/ffindex/src/CMakeFiles/ffindex_modify.dir/ffindex_modify.c.o
Linking C executable ffindex_from_fasta_with_split
Building C object lib/ffindex/src/CMakeFiles/ffindex_order.dir/ffindex_order.c.o
Linking C executable ffindex_get
[ 37%] Linking C executable ffindex_modify
Built target ffindex_from_fasta_with_split
Linking C executable ffindex_order
Scanning dependencies of target ffindex_reduce
[ 39%] [ 39%] [ 39%] [ 39%] Built target ffindex_order
Built target ffindex_get
Built target ffindex_modify
Building C object lib/ffindex/src/CMakeFiles/ffindex_reduce.dir/ffindex_reduce.c.o
Scanning dependencies of target ffindex_unpack
Scanning dependencies of target HH_OBJECTS
Linking C executable ffindex_reduce
[ 40%] Building C object lib/ffindex/src/CMakeFiles/ffindex_unpack.dir/ffindex_unpack.c.o
[ 40%] Built target ffindex_reduce
Linking C executable ffindex_unpack
[ 40%] Built target ffindex_unpack
[ 41%] [ 45%] [ 45%] [ 45%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhmatrices.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhblits.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhdecl.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhhit.cpp.o
[ 47%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhsearch.cpp.o
[ 48%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhalign.cpp.o
[ 50%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhhitlist.cpp.o
[ 51%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhposteriordecoder.cpp.o
[ 52%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhutil.cpp.o
[ 54%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/util.cpp.o
[ 55%] [ 56%] [ 58%] [ 59%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhalignment.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhforwardalgorithm.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhhmm.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhposteriordecoderrunner.cpp.o
[ 60%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhviterbialgorithm.cpp.o
[ 62%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhfullalignment.cpp.o
[ 63%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhhmmsimd.cpp.o
[ 64%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhposteriormatrix.cpp.o
[ 66%] [ 67%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhviterbi.cpp.o
[ 68%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhbacktracemac.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhmacalgorithm.cpp.o
[ 70%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhprefilter.cpp.o
[ 71%] [ 72%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhviterbimatrix.cpp.o
Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhbackwardalgorithm.cpp.o
[ 74%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/ffindexdatabase.cpp.o
[ 75%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhdatabase.cpp.o
[ 77%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhhalfalignment.cpp.o
[ 78%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhviterbirunner.cpp.o
[ 79%] Building CXX object src/CMakeFiles/HH_OBJECTS.dir/hhfunc.cpp.o
Linking CXX static library libHH_OBJECTS.a
[ 79%] Built target HH_OBJECTS
Scanning dependencies of target hhalign
Scanning dependencies of target cstranslate
Scanning dependencies of target hhalign_mpi
Scanning dependencies of target cstranslate_mpi
[ 81%] [ 82%] Building CXX object src/CMakeFiles/hhalign.dir/hhblits_app.cpp.o
Building CXX object src/CMakeFiles/hhalign_mpi.dir/hhblits_mpi.cpp.o
[ 83%] [ 85%] Building CXX object src/CMakeFiles/cstranslate_mpi.dir/cs/cstranslate_mpi_app.cc.o
Building CXX object src/CMakeFiles/cstranslate.dir/cs/cstranslate_app.cc.o
Linking CXX executable hhalign
Linking CXX executable hhalign_mpi
/bin/ld : ne peut trouver -lmpq
collect2: erreur: ld a retourné 1 code d'état d'exécution
make[2]: *** [src/hhalign_mpi] Erreur 1
make[1]: *** [src/CMakeFiles/hhalign_mpi.dir/all] Erreur 2
make[1]: *** Attente des tâches non terminées....
[ 85%] Built target hhalign
Linking CXX executable cstranslate
[ 85%] Built target cstranslate
Linking CXX executable cstranslate_mpi
/bin/ld : ne peut trouver -lmpq
collect2: erreur: ld a retourné 1 code d'état d'exécution
make[2]: *** [src/cstranslate_mpi] Erreur 1
make[1]: *** [src/CMakeFiles/cstranslate_mpi.dir/all] Erreur 2
make: *** [all] Erreur 2
```
Soory for errors inf french but english version can be found in [Original post](https://github.com/soedinglab/hh-suite/issues/64#issue-241216335)

#### second cmake iteration

```
cmake -DCMAKE_INSTALL_PREFIX=. ..
-- Compiler is GNU
-- Found MPI_C: /usr/local/public/openmpi-2.1.0/lib/libmpi.so
-- Found MPI_CXX: /usr/local/public/openmpi-2.1.0/lib/libmpi.so
-- Found OpenMP
-- Configuring done
-- Generating done
-- Build files have been written to: .../hh-suite/build
```

#### second make 

```
make -j 4 && make install
Scanning dependencies of target mpq
[  3%] Built target generated
[  6%] Built target ffindex
[  7%] Built target A3M_COMPRESS
[  9%] Building C object lib/ffindex/src/mpq/CMakeFiles/mpq.dir/mpq.c.o
[ 18%] [ 21%] [ 21%] Built target CS_OBJECTS
Built target hhviterbialgorithm_with_celloff
Built target hhviterbialgorithm_and_ss
Linking C static library libmpq.a
[ 22%] Built target a3m_database_extract
[ 23%] Built target hhviterbialgorithm_with_celloff_and_ss
[ 25%] Built target a3m_database_filter
[ 25%] Built target mpq
[ 26%] Built target a3m_extract
[ 27%] Built target a3m_database_reduce
Scanning dependencies of target ffindex_apply_mpi
[ 28%] Built target a3m_reduce
[ 30%] Built target ffindex_apply
[ 31%] Built target ffindex_build
[ 34%] [ 34%] Built target ffindex_from_fasta
Building C object lib/ffindex/src/CMakeFiles/ffindex_apply_mpi.dir/ffindex_apply_mpi.c.o
[ 35%] Built target ffindex_from_fasta_with_split
[ 36%] Built target ffindex_get
[ 38%] Built target ffindex_modify
[ 39%] Built target ffindex_order
[ 40%] Built target ffindex_reduce
[ 42%] Built target ffindex_unpack
Linking C executable ffindex_apply_mpi
[ 80%] Built target HH_OBJECTS
Scanning dependencies of target cstranslate_mpi
[ 82%] [ 82%] [ 82%] Built target hhalign
Built target cstranslate
Built target ffindex_apply_mpi
Linking CXX executable cstranslate_mpi
Scanning dependencies of target hhblits
Scanning dependencies of target hhalign_mpi
Scanning dependencies of target hhalign_omp
Linking CXX executable hhalign_mpi
[ 84%] Built target cstranslate_mpi
Scanning dependencies of target hhblits_ca3m
[ 85%] Built target hhalign_mpi
[ 86%] [ 88%] Building CXX object src/CMakeFiles/hhalign_omp.dir/hhblits_omp.cpp.o
Building CXX object src/CMakeFiles/hhblits.dir/hhblits_app.cpp.o
Scanning dependencies of target hhblits_mpi
[ 89%] Building CXX object src/CMakeFiles/hhblits_ca3m.dir/hhblits_ca3m.cpp.o
[ 90%] Building CXX object src/CMakeFiles/hhblits_mpi.dir/hhblits_mpi.cpp.o
Linking CXX executable hhblits
Linking CXX executable hhalign_omp
[ 90%] Built target hhblits
Scanning dependencies of target hhblits_omp
Linking CXX executable hhblits_ca3m
Linking CXX executable hhblits_mpi
[ 90%] Built target hhalign_omp
Scanning dependencies of target hhconsensus
[ 92%] [ 92%] Building CXX object src/CMakeFiles/hhblits_omp.dir/hhblits_omp.cpp.o
Built target hhblits_ca3m
Scanning dependencies of target hhfilter
[ 92%] Built target hhblits_mpi
Scanning dependencies of target hhmake
[ 93%] Building CXX object src/CMakeFiles/hhconsensus.dir/hhconsensus.cpp.o
[ 94%] Building CXX object src/CMakeFiles/hhfilter.dir/hhfilter.cpp.o
[ 96%] Building CXX object src/CMakeFiles/hhmake.dir/hhmake.cpp.o
Linking CXX executable hhblits_omp
Linking CXX executable hhfilter
Linking CXX executable hhconsensus
[ 96%] Built target hhfilter
Linking CXX executable hhmake
[ 96%] Scanning dependencies of target hhsearch
Built target hhblits_omp
Scanning dependencies of target hhsearch_mpi
[ 96%] Built target hhconsensus
Scanning dependencies of target hhsearch_omp
[ 96%] Built target hhmake
[ 97%] Building CXX object src/CMakeFiles/hhsearch.dir/hhblits_app.cpp.o
[ 98%] Building CXX object src/CMakeFiles/hhsearch_mpi.dir/hhblits_mpi.cpp.o
[100%] Building CXX object src/CMakeFiles/hhsearch_omp.dir/hhblits_omp.cpp.o
Linking CXX executable hhsearch
Linking CXX executable hhsearch_mpi
[100%] Built target hhsearch
Linking CXX executable hhsearch_omp
[100%] Built target hhsearch_mpi
[100%] Built target hhsearch_omp
[  2%] Built target ffindex
[  3%] Built target ffindex_apply
[  5%] Built target mpq
[  6%] Built target ffindex_apply_mpi
[  7%] Built target ffindex_build
[  9%] Built target ffindex_from_fasta
[ 10%] Built target ffindex_from_fasta_with_split
[ 11%] Built target ffindex_get
[ 13%] Built target ffindex_modify
[ 14%] Built target ffindex_order
[ 15%] Built target ffindex_reduce
[ 17%] Built target ffindex_unpack
[ 21%] Built target generated
[ 22%] Built target A3M_COMPRESS
[ 23%] Built target hhviterbialgorithm_and_ss
[ 25%] Built target hhviterbialgorithm_with_celloff
[ 34%] Built target CS_OBJECTS
[ 35%] Built target hhviterbialgorithm_with_celloff_and_ss
[ 73%] Built target HH_OBJECTS
[ 75%] Built target a3m_database_extract
[ 76%] Built target a3m_database_filter
[ 77%] Built target a3m_database_reduce
[ 78%] Built target a3m_extract
[ 80%] Built target a3m_reduce
[ 81%] Built target cstranslate
[ 82%] Built target cstranslate_mpi
[ 84%] Built target hhalign
[ 85%] Built target hhalign_mpi
[ 86%] Built target hhalign_omp
[ 88%] Built target hhblits
[ 89%] Built target hhblits_ca3m
[ 90%] Built target hhblits_mpi
[ 92%] Built target hhblits_omp
[ 93%] Built target hhconsensus
[ 94%] Built target hhfilter
[ 96%] Built target hhmake
[ 97%] Built target hhsearch
[ 98%] Built target hhsearch_mpi
[100%] Built target hhsearch_omp
Install the project...
-- Install configuration: "Release"
-- Installing: .../hh-suite/build/bin/ffindex_apply_mpi
-- Removed runtime path from ".../hh-suite/build/bin/ffindex_apply_mpi"
-- Installing: .../hh-suite/build/bin/ffindex_reduce
-- Installing: .../hh-suite/build/bin/ffindex_apply
-- Installing: .../hh-suite/build/bin/ffindex_build
-- Installing: .../hh-suite/build/bin/ffindex_from_fasta
-- Installing: .../hh-suite/build/bin/ffindex_get
-- Installing: .../hh-suite/build/bin/ffindex_modify
-- Installing: .../hh-suite/build/bin/ffindex_unpack
-- Installing: .../hh-suite/build/bin/ffindex_order
-- Installing: .../hh-suite/build/bin/ffindex_from_fasta_with_split
-- Installing: .../hh-suite/build/data/context_data.crf
-- Installing: .../hh-suite/build/data/context_data.lib
-- Installing: .../hh-suite/build/data/cs219.lib
-- Installing: .../hh-suite/build/data/do_not_delete
-- Installing: .../hh-suite/build/data/do_not_delete.phr
-- Installing: .../hh-suite/build/data/do_not_delete.pin
-- Installing: .../hh-suite/build/data/do_not_delete.psq
-- Installing: .../hh-suite/build/bin/hhblits
-- Installing: .../hh-suite/build/bin/hhmake
-- Installing: .../hh-suite/build/bin/hhfilter
-- Installing: .../hh-suite/build/bin/hhsearch
-- Installing: .../hh-suite/build/bin/hhalign
-- Installing: .../hh-suite/build/bin/hhconsensus
-- Installing: .../hh-suite/build/bin/a3m_extract
-- Installing: .../hh-suite/build/bin/a3m_reduce
-- Installing: .../hh-suite/build/bin/a3m_database_reduce
-- Installing: .../hh-suite/build/bin/a3m_database_extract
-- Installing: .../hh-suite/build/bin/a3m_database_filter
-- Installing: .../hh-suite/build/bin/cstranslate
-- Installing: .../hh-suite/build/bin/hhblits_omp
-- Installing: .../hh-suite/build/bin/hhsearch_omp
-- Installing: .../hh-suite/build/bin/hhalign_omp
-- Installing: .../hh-suite/build/bin/hhblits_ca3m
-- Installing: .../hh-suite/build/bin/hhblits_mpi
-- Removed runtime path from ".../hh-suite/build/bin/hhblits_mpi"
-- Installing: .../hh-suite/build/bin/hhsearch_mpi
-- Removed runtime path from ".../hh-suite/build/bin/hhsearch_mpi"
-- Installing: .../hh-suite/build/bin/hhalign_mpi
-- Removed runtime path from ".../hh-suite/build/bin/hhalign_mpi"
-- Installing: .../hh-suite/build/bin/cstranslate_mpi
-- Removed runtime path from ".../hh-suite/build/bin/cstranslate_mpi"
-- Installing: .../hh-suite/build/scripts/a3m.py
-- Installing: .../hh-suite/build/scripts/addss.pl
-- Installing: .../hh-suite/build/scripts/Align.pm
-- Installing: .../hh-suite/build/scripts/check_a3m.py
-- Installing: .../hh-suite/build/scripts/cif2fasta.py
-- Installing: .../hh-suite/build/scripts/create_profile_from_hhm.pl
-- Installing: .../hh-suite/build/scripts/create_profile_from_hmmer.pl
-- Installing: .../hh-suite/build/scripts/ffindex.py
-- Installing: .../hh-suite/build/scripts/get_a3m_size.py
-- Installing: .../hh-suite/build/scripts/hh_reader.py
-- Installing: .../hh-suite/build/scripts/hhmakemodel.pl
-- Installing: .../hh-suite/build/scripts/hhmakemodel.py
-- Installing: .../hh-suite/build/scripts/HHPaths.pm
-- Installing: .../hh-suite/build/scripts/hhsuitedb.py
-- Installing: .../hh-suite/build/scripts/mergeali.pl
-- Installing: .../hh-suite/build/scripts/multithread.pl
-- Installing: .../hh-suite/build/scripts/pdb2fasta.pl
-- Installing: .../hh-suite/build/scripts/pdbfilter.pl
-- Installing: .../hh-suite/build/scripts/pdbfilter.py
-- Installing: .../hh-suite/build/scripts/reformat.pl
-- Installing: .../hh-suite/build/scripts/renumberpdb.pl
-- Installing: .../hh-suite/build/scripts/splitfasta.pl
```

**Comment by SmartBioInf** [comment]
Informations are below _(sorry operaying system is configured in french and I don't have root privileges to change it)_

I installed hh-suite few months ago (v3.3.0-5-g57c8707 commit 57c8707149031cc9f8edceba362c71a3762bdbf8) and hadn't encountered this problem.


#### cmake

```
cmake --version
cmake version 2.8.12.2
```

#### gcc

```
gcc -v
Utilisation des specs internes.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configuré avec: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Modèle de thread: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
```

#### Operating system 

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by milot-mirdita** [comment]
Thanks. I can somewhat reproduce it with the centos:7 docker image. I think that's an issue with either the ancient centos cmake or openmpi packages. I can't reproduce the behavior where it find an incomplete openmpi installation though.

Running `PATH="$PATH:/usr/lib64/openmpi/bin" cmake ..` seems to do correct MPI detection on the first shot. I found someone else facing this issue here: https://stackoverflow.com/questions/52485453/cmake-cant-find-default-mpi-install-on-stock-centos-7

I don't think we can do much in the hhsuite against this problem though.

**Comment by milot-mirdita** [comment]
Okay there was actually something wrong. I fixed the issue in https://github.com/soedinglab/hh-suite/commit/54f5d3affbc7956390f535622c69f5f3f4226c2f. Thanks for the bug report.

**Comment by SmartBioInf** [comment]
Thanks for your reactivity. I just tested the corrected version, it works.
